org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.useAndroidX=true
org.gradle.vfs.watch=false
org.gradle.daemon=false
org.gradle.workers.max=1
android.enableR8.fullMode=false
android.experimental.art.profile.r8.rewriting=false
android.lint.checkDependencies=false
